import type { Metadata } from "next";
import { Rubik, Numans, Roboto } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const rubik = Rubik({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700", "900"],
});

const numans = Numans({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={
					rubik.className + " " + numans.className + " " + roboto.className
				}
			>
				<div className="font-impact"> {children}</div>
			</body>
		</html>
	);
}
